# Generated by Django 4.0.2 on 2022-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Util',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project name')),
                ('picture', models.ImageField(upload_to='media', verbose_name='Project picture')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon name')),
                ('author', models.CharField(max_length=50, verbose_name='Project author')),
                ('is_organization', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('html_content', models.TextField()),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('api_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Util',
                'verbose_name_plural': 'Utils',
            },
        ),
    ]
