# Generated by Django 4.0.2 on 2022-02-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='util',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Project picture'),
        ),
    ]
