# Generated by Django 4.0.2 on 2022-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_util_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='util',
            name='picture',
            field=models.ImageField(default='sfsfsdfsf', upload_to='media', verbose_name='Project picture'),
            preserve_default=False,
        ),
    ]
